# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iKid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JellyGif'
  pod 'SwiftGifOrigin'

  # Pods for iKid

  target 'iKidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iKidUITests' do
    # Pods for testing
  end

end
